name: Release dylib

on:
  release:
    types: [published]

jobs:
  release-dylib:
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      DYLIB_NAME: "libstandardloop-logger.dylib"
      DYLIB_ZIP: "libstandardloop-logger.dylib.zip"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: echo vars
        run: |
          echo ${{ env.DYLIB_NAME }}
          echo ${{ env.DYLIB_ZIP }}

      - name: Build the dylib
        run: |
          make build_release

      - name: Archive dylib
        run: |
          zip ${{ env.DYLIB_ZIP }} ${{ env.DYLIB_NAME }}

      - name: Create dylib Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.DYLIB_ZIP }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dylib as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DYLIB_ZIP }}
          path: ${{ env.DYLIB_ZIP }}
