name: Release C Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile C code
      run: |
        make build_release

    - name: Create Release and Upload Binary
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: libstandardloop-logger.dylib
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for authentication
